import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        outline: "#717c82",
        "on-secondary-fixed-variant": "#4d5d73",
        "on-error": "#fff7f6",
        "primary-dim": "#4a5268",
        "on-primary-fixed-variant": "#535b71",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#565873",
        "secondary-fixed": "#d3e4fe",
        "on-error-container": "#752121",
        "tertiary-fixed": "#dcddfe",
        "surface-container-highest": "#d9e4ea",
        "surface-tint": "#565e74",
        primary: "#565e74",
        "error-dim": "#4e0309",
        "tertiary-fixed-dim": "#cecfef",
        error: "#9f403d",
        "on-secondary-container": "#435368",
        "surface-variant": "#d9e4ea",
        "on-surface-variant": "#566166",
        "secondary-container": "#d3e4fe",
        "surface-container": "#e8eff3",
        "secondary-fixed-dim": "#c5d6f0",
        "on-secondary-fixed": "#314055",
        "primary-fixed": "#dae2fd",
        "secondary-dim": "#44546a",
        "inverse-on-surface": "#9a9d9f",
        "on-tertiary-fixed": "#393c55",
        "inverse-surface": "#0b0f10",
        "on-tertiary": "#fbf8ff",
        "on-tertiary-container": "#4c4e69",
        surface: "#f7f9fb",
        "surface-dim": "#cfdce3",
        "on-primary": "#f7f7ff",
        "primary-container": "#dae2fd",
        "outline-variant": "#a9b4b9",
        "primary-fixed-dim": "#ccd4ee",
        "on-secondary": "#f7f9ff",
        tertiary: "#5b5d78",
        "on-primary-fixed": "#373f54",
        "tertiary-dim": "#4f516c",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#dae2fd",
        secondary: "#506076",
        "surface-container-high": "#e1e9ee",
        "error-container": "#fe8983",
        "on-background": "#2a3439",
        "on-surface": "#2a3439",
        "surface-container-low": "#f0f4f7",
        "on-primary-container": "#4a5167",
        "tertiary-container": "#dcddfe",
        background: "#f7f9fb",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
} satisfies Config;

